export type Meme = {
  id: string
  term: string
  meaning: string
  image: string
  creator: string
  bookmarks: number
  tags: string[]
  /** How the image should fill the square card. Defaults to "cover". */
  fit?: "cover" | "contain"
  /** Marks adult / mature content that is hidden from new users by default. */
  nsfw?: boolean
}

export function getMemeById(id: string): Meme | undefined {
  return hotMemes.find((m) => m.id === id)
}

export function getSimilarMemes(meme: Meme, limit = 6): Meme[] {
  const scored = hotMemes
    .filter((m) => m.id !== meme.id)
    .map((m) => ({
      meme: m,
      score: m.tags.filter((t) => meme.tags.includes(t)).length,
    }))
    .sort((a, b) => b.score - a.score || b.meme.bookmarks - a.meme.bookmarks)

  return scored.slice(0, limit).map((s) => s.meme)
}

export const hotMemes: Meme[] = [
  {
    id: "doge",
    term: "Doge",
    meaning: "A Shiba Inu paired with broken-English inner-monologue captions like 'much wow' and 'so scare'.",
    image: "/memes/kym-doge.jpg",
    creator: "knowyourmeme",
    bookmarks: 45210,
    tags: ["classic", "animals", "viral"],
  },
  {
    id: "navy-seal",
    term: "Navy Seal Copypasta",
    meaning: "An over-the-top threatening rant copypasta parodying tough-guy internet arguments.",
    image: "/memes/kym-navyseal.jpg",
    creator: "knowyourmeme",
    bookmarks: 41290,
    tags: ["classic", "copypasta", "viral"],
  },
  {
    id: "slender-man",
    term: "Slender Man",
    meaning: "A faceless, tall paranormal figure born from a creepypasta forum contest. Also used as a way to describe a tall or lanky slightly offputting person.",
    image: "/memes/kym-slenderman.jpg",
    creator: "knowyourmeme",
    bookmarks: 33760,
    tags: ["classic", "horror", "creepypasta"],
  },
  {
    id: "lenny-face",
    term: "Lenny Face",
    meaning: "The ( ͡° ͜ʖ ͡°) emoticon used to imply innuendo, mischief, or knowing smugness.",
    image: "/memes/kym-lennyface.jpg",
    creator: "knowyourmeme",
    bookmarks: 29540,
    tags: ["classic", "emoticon", "viral"],
    fit: "contain",
  },
  {
    id: "forever-alone",
    term: "Forever Alone",
    meaning: "A rage-comic face expressing loneliness and disappointment, often self-deprecating.",
    image: "/memes/kym-foreveralone.jpg",
    creator: "knowyourmeme",
    bookmarks: 27180,
    tags: ["classic", "rage", "relatable"],
  },
  {
    id: "gyatt",
    term: "Gyatt",
    meaning: "An exclamation of surprise or admiration, usually reacting to something impressive.",
    image: "/memes/kym-gyatt.jpg",
    creator: "knowyourmeme",
    bookmarks: 12483,
    tags: ["reaction", "hype", "genz"],
    fit: "contain",
  },
  {
    id: "rizz",
    term: "Rizz",
    meaning: "Charisma or charm, especially the skill of attracting a romantic interest.",
    image: "/memes/kym-rizz.jpg",
    creator: "knowyourmeme",
    bookmarks: 20194,
    tags: ["charm", "dating", "viral"],
    fit: "contain",
  },
  {
    id: "ohio",
    term: "Down in Ohio",
    meaning: "Used to describe something weird, chaotic, or absurd happening.",
    image: "/memes/kym-ohio.jpg",
    creator: "knowyourmeme",
    bookmarks: 8721,
    tags: ["chaos", "absurd", "meme"],
  },
  {
    id: "sigma",
    term: "Sigma",
    meaning: "A self-reliant, lone-wolf personality that plays by its own rules.",
    image: "/memes/kym-sigma.jpg",
    creator: "knowyourmeme",
    bookmarks: 15320,
    tags: ["mindset", "grind", "genz"],
  },
  {
    id: "skibidi",
    term: "Skibidi",
    meaning: "Nonsense slang from a viral series; can mean cool, bad, or dumb depending on context.",
    image: "/memes/kym-skibidi.jpg",
    creator: "knowyourmeme",
    bookmarks: 31005,
    tags: ["viral", "absurd", "brainrot"],
  },
  {
    id: "fanum",
    term: "Fanum Tax",
    meaning: "Jokingly stealing a bite of a friend's food.",
    image: "/memes/kym-fanum.jpg",
    creator: "knowyourmeme",
    bookmarks: 9640,
    tags: ["food", "friends", "meme"],
    fit: "contain",
  },
  {
    id: "delulu",
    term: "Delulu",
    meaning: "Short for delusional — believing in something unrealistic, often as a joke.",
    image: "/memes/kym-delulu.jpg",
    creator: "knowyourmeme",
    bookmarks: 17812,
    tags: ["mood", "funny", "genz"],
    fit: "contain",
  },
  {
    id: "mewing",
    term: "Mewing",
    meaning: "Pressing your tongue to the roof of your mouth to define your jawline.",
    image: "/memes/kym-mewing.jpg",
    creator: "knowyourmeme",
    bookmarks: 6455,
    tags: ["looksmax", "trend", "gym"],
    fit: "contain",
  },
  {
    id: "npc",
    term: "NPC",
    meaning: "Someone seen as acting without independent thought, like a background game character.",
    image: "/memes/kym-npc.jpg",
    creator: "knowyourmeme",
    bookmarks: 11290,
    tags: ["gaming", "roast", "meme"],
  },
  {
    id: "cooked",
    term: "Cooked",
    meaning: "Being in serious trouble or completely exhausted.",
    image: "/memes/kym-cooked.png",
    creator: "knowyourmeme",
    bookmarks: 8033,
    tags: ["mood", "relatable", "genz"],
  },
  {
    id: "glaze",
    term: "Glazing",
    meaning: "Excessively praising or hyping someone up.",
    image: "/memes/kym-glaze.jpg",
    creator: "knowyourmeme",
    bookmarks: 7418,
    tags: ["hype", "roast", "meme"],
  },
  {
    id: "aura",
    term: "Aura Points",
    meaning: "Imaginary score for how cool or impressive your actions are.",
    image: "/memes/kym-aura.jpg",
    creator: "knowyourmeme",
    bookmarks: 13977,
    tags: ["vibes", "cool", "genz"],
  },
  {
    id: "gigachad",
    term: "Gigachad",
    meaning:
      "An idealized, hyper-masculine man used to represent peak confidence or being objectively correct.",
    image: "/memes/kym-gigachad.jpg",
    creator: "knowyourmeme",
    bookmarks: 38210,
    tags: ["reaction", "based", "viral"],
  },
  {
    id: "kai-cenat",
    term: "Kai Cenat",
    meaning:
      "Twitch megastar whose high-energy streams and reactions fuel countless clips and Gen-Z slang.",
    image: "/memes/kym-kai-cenat.jpg",
    creator: "knowyourmeme",
    bookmarks: 26540,
    tags: ["streamer", "reaction", "genz"],
  },
  {
    id: "ishowspeed",
    term: "IShowSpeed",
    meaning:
      "Explosive streamer famous for over-the-top reactions, screaming, and viral livestream moments.",
    image: "/memes/kym-ishowspeed.jpg",
    creator: "knowyourmeme",
    bookmarks: 29880,
    tags: ["streamer", "reaction", "viral"],
  },
  {
    id: "john-pork",
    term: "John Pork",
    meaning:
      "A surreal pig-headed man in a suit who 'calls' you — an absurdist edit that became a running gag.",
    image: "/memes/kym-john-pork.jpg",
    creator: "knowyourmeme",
    bookmarks: 15720,
    tags: ["absurd", "surreal", "brainrot"],
  },
  {
    id: "quandale-dingle",
    term: "Quandale Dingle",
    meaning:
      "A surreal name-and-face meme from a leaked school photo, spawning chaotic 'Quandale Dingle here' skits.",
    image: "/memes/kym-quandale-dingle.jpg",
    creator: "knowyourmeme",
    bookmarks: 18930,
    tags: ["absurd", "brainrot", "viral"],
  },
  {
    id: "amogus",
    term: "Amogus",
    meaning:
      "A deliberately misspelled Among Us crewmate, shorthand for calling something or someone 'sus'.",
    image: "/memes/kym-amogus.jpg",
    creator: "knowyourmeme",
    bookmarks: 42110,
    tags: ["gaming", "absurd", "viral"],
  },
  {
    id: "huggy-wuggy",
    term: "Huggy Wuggy",
    meaning: "The toothy blue monster from Poppy Playtime that became a horror-meme mascot.",
    image: "/memes/kym-huggy-wuggy.jpg",
    creator: "knowyourmeme",
    bookmarks: 12440,
    tags: ["horror", "gaming", "meme"],
    fit: "contain",
  },
  {
    id: "big-chungus",
    term: "Big Chungus",
    meaning: "A chonky Bugs Bunny image used as the ultimate 'absolute unit' reaction meme.",
    image: "/memes/kym-big-chungus.jpg",
    creator: "knowyourmeme",
    bookmarks: 33110,
    tags: ["reaction", "classic", "viral"],
  },
  {
    id: "pizza-tower",
    term: "Pizza Tower",
    meaning:
      "The frantic indie game whose Peppino animations and soundtrack fueled a wave of hyperactive edits.",
    image: "/memes/kym-pizza-tower.jpg",
    creator: "knowyourmeme",
    bookmarks: 14260,
    tags: ["gaming", "brainrot", "meme"],
    fit: "contain",
  },
  {
    id: "backrooms",
    term: "The Backrooms",
    meaning:
      "Endless liminal yellow office rooms from a creepypasta about 'noclipping' out of reality.",
    image: "/memes/kym-backrooms.jpg",
    creator: "knowyourmeme",
    bookmarks: 27650,
    tags: ["horror", "creepypasta", "viral"],
  },
  {
    id: "goofy-ahh",
    term: "Goofy Ahh",
    meaning: "An intensifier tacked onto anything to make it sound silly, like 'goofy ahh haircut'.",
    image: "/memes/kym-goofy-ahh.jpg",
    creator: "knowyourmeme",
    bookmarks: 16980,
    tags: ["genz", "funny", "brainrot"],
    fit: "contain",
  },
  {
    id: "morbin-time",
    term: "Morbin Time",
    meaning: "Ironic hype catchphrase ('It's Morbin Time') born from mocking the movie Morbius.",
    image: "/memes/kym-morbin-time.jpg",
    creator: "knowyourmeme",
    bookmarks: 21030,
    tags: ["ironic", "viral", "meme"],
  },
  {
    id: "ugandan-knuckles",
    term: "Ugandan Knuckles",
    meaning: "A crude Knuckles model swarming VRChat while asking 'do you know da wae?'",
    image: "/memes/kym-ugandan-knuckles.jpg",
    creator: "knowyourmeme",
    bookmarks: 19470,
    tags: ["gaming", "classic", "viral"],
  },
  {
    id: "andrew-tate",
    term: "Andrew Tate",
    meaning: "Divisive online personality and former kickboxer known for hyper-masculine 'Top G' clips and hustle-culture soundbites.",
    image: "/memes/kym-andrew-tate.jpg",
    creator: "knowyourmeme",
    bookmarks: 22126,
    tags: ["people", "controversial", "viral"],
  },
  {
    id: "goon-cave",
    nsfw: true,
    term: "Goon Cave",
    meaning: "Ironic slang for a dim room where someone retreats to endlessly scroll or indulge online.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 16875,
    tags: ["slang", "ironic", "brainrot"],
  },
  {
    id: "freddy-fazbear",
    term: "Freddy Fazbear",
    meaning: "The animatronic bear mascot of the Five Nights at Freddy's horror game series.",
    image: "/memes/kym-freddy-fazbear.jpg",
    creator: "knowyourmeme",
    bookmarks: 21294,
    tags: ["gaming", "horror", "mascot"],
  },
  {
    id: "colleen-ballinger",
    term: "Colleen Ballinger",
    meaning: "YouTuber behind the character Miranda Sings, later the subject of a widely mocked ukulele apology video.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 20357,
    tags: ["people", "youtube", "controversial"],
  },
  {
    id: "smurf-cat",
    term: "Smurf Cat",
    meaning: "A surreal blue mushroom-cat creature (Shailushai) that went viral in 'vs.' matchup edits.",
    image: "/memes/kym-smurf-cat.jpg",
    creator: "knowyourmeme",
    bookmarks: 23104,
    tags: ["animals", "surreal", "viral"],
  },
  {
    id: "strawberry-elephant",
    term: "Strawberry Elephant",
    meaning: "A pink strawberry-textured elephant character paired against Smurf Cat in viral versus edits.",
    image: "/memes/kym-strawberry-elephant.jpg",
    creator: "knowyourmeme",
    bookmarks: 16103,
    tags: ["animals", "surreal", "viral"],
  },
  {
    id: "blud",
    term: "Blud",
    meaning: "British-origin slang for 'bro,' used mockingly as in 'blud thinks he's him.'",
    image: "/memes/kym-blud.jpg",
    creator: "knowyourmeme",
    bookmarks: 22433,
    tags: ["slang", "genz", "brainrot"],
  },
  {
    id: "shmlawg",
    term: "Shmlawg",
    meaning: "An IShowSpeed catchphrase and mangled pronunciation turned recurring audio meme.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 12845,
    tags: ["slang", "streamer", "brainrot"],
  },
  {
    id: "whole-bunch-of-turbulence",
    term: "A Whole Bunch of Turbulence",
    meaning: "A viral audio clip of a passenger calmly narrating rough flight turbulence.",
    image: "/memes/kym-whole-bunch-of-turbulence.jpg",
    creator: "knowyourmeme",
    bookmarks: 15030,
    tags: ["audio", "viral", "brainrot"],
  },
  {
    id: "ambatukam",
    nsfw: true,
    term: "Ambatukam",
    meaning: "A garbled 'I'm about to cum' soundboard phrase from streamer DreamyBull, used absurdly.",
    image: "/memes/kym-ambatukam.jpg",
    creator: "knowyourmeme",
    bookmarks: 13787,
    tags: ["audio", "absurd", "brainrot"],
  },
  {
    id: "bro-thinks-hes-carti",
    term: "Bro Really Thinks He's Carti",
    meaning: "A mocking phrase aimed at someone acting like rapper Playboi Carti.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 17036,
    tags: ["slang", "music", "brainrot"],
  },
  {
    id: "hitting-the-griddy",
    term: "Hitting the Griddy",
    meaning: "A celebratory dance with swinging arms and shuffling feet popularized in sports and Fortnite.",
    image: "/memes/kym-hitting-the-griddy.jpg",
    creator: "knowyourmeme",
    bookmarks: 24083,
    tags: ["dance", "sports", "viral"],
  },
  {
    id: "the-ocky-way",
    term: "The Ocky Way",
    meaning: "NYC bodega worker who narrates over-the-top custom sandwiches, ending with 'you feel me.'",
    image: "/memes/kym-the-ocky-way.jpg",
    creator: "knowyourmeme",
    bookmarks: 19136,
    tags: ["food", "viral", "genz"],
  },
  {
    id: "garten-of-banban",
    term: "Garten of Banban",
    meaning: "A widely ridiculed horror-mascot kids' game known for its low-effort reputation.",
    image: "/memes/kym-garten-of-banban.jpg",
    creator: "knowyourmeme",
    bookmarks: 17734,
    tags: ["gaming", "horror", "brainrot"],
  },
  {
    id: "no-edging-in-class",
    nsfw: true,
    term: "No Edging in Class",
    meaning: "An absurdist Gen Alpha classroom-rules catchphrase used ironically.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 12487,
    tags: ["slang", "ironic", "brainrot"],
  },
  {
    id: "not-the-mosquito-again",
    term: "Not the Mosquito Again",
    meaning: "A relatable reaction phrase about a buzzing mosquito interrupting your sleep.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 10432,
    tags: ["relatable", "funny", "brainrot"],
  },
  {
    id: "bussin",
    term: "Bussin",
    meaning: "Slang meaning something (usually food) is extremely good or delicious.",
    image: "/memes/kym-bussin.png",
    creator: "knowyourmeme",
    bookmarks: 25200,
    tags: ["slang", "food", "genz"],
  },
  {
    id: "axel-in-harlem",
    term: "Axel in Harlem",
    meaning: "A viral animated meme set to the Cotton Eye Joe / Crazy Frog remix built around the name Axel.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 9884,
    tags: ["music", "absurd", "brainrot"],
  },
  {
    id: "whopper-whopper",
    term: "Whopper Whopper",
    meaning: "Burger King's endlessly repeated 'Whopper Whopper' jingle that became an earworm meme.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 23001,
    tags: ["ad", "music", "viral"],
  },
  {
    id: "buckle-my-shoe",
    term: "1 2 Buckle My Shoe",
    meaning: "A menacing nursery-rhyme edit trend counting up over ominous visuals.",
    image: "/memes/kym-buckle-my-shoe.jpg",
    creator: "knowyourmeme",
    bookmarks: 12931,
    tags: ["audio", "edit", "brainrot"],
  },
  {
    id: "adin-ross",
    term: "Adin Ross",
    meaning: "Controversial livestreamer known for celebrity streams and frequent platform bans.",
    image: "/memes/kym-adin-ross.jpg",
    creator: "knowyourmeme",
    bookmarks: 20362,
    tags: ["people", "streamer", "controversial"],
  },
  {
    id: "sin-city",
    term: "Sin City",
    meaning: "The 'Sin City about to explode' filter trend applied to chaotic scenes.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 11856,
    tags: ["edit", "trend", "brainrot"],
  },
  {
    id: "monday-left-me-broken",
    term: "Monday Left Me Broken",
    meaning: "A melodramatic sped-up cover of 'Just Can't Get Enough' used over sad edits.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 12721,
    tags: ["music", "edit", "brainrot"],
  },
  {
    id: "quirked-up-white-boy",
    term: "Quirked Up White Boy",
    meaning: "A viral brainrot copypasta describing a 'quirked-up white boy' who is 'goated with the sauce.'",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 16766,
    tags: ["copypasta", "brainrot", "viral"],
  },
  {
    id: "grimace-shake",
    term: "Grimace Shake",
    meaning: "A McDonald's purple shake turned horror-trend where people 'collapse' after drinking it.",
    image: "/memes/kym-grimace-shake.jpg",
    creator: "knowyourmeme",
    bookmarks: 23517,
    tags: ["food", "horror", "viral"],
  },
  {
    id: "kiki-do-you-love-me",
    term: "Kiki Do You Love Me",
    meaning: "Drake's 'In My Feelings' lyric that launched the viral #KiKiChallenge dance.",
    image: "/memes/kym-kiki-do-you-love-me.jpg",
    creator: "knowyourmeme",
    bookmarks: 25572,
    tags: ["music", "dance", "viral"],
  },
  {
    id: "nathaniel-b",
    term: "Nathaniel B",
    meaning: "A catchy name-chant audio ('Nathaniel B, oh Nathaniel B') used in loop edits.",
    image: "/memes/kym-nathaniel-b.jpg",
    creator: "knowyourmeme",
    bookmarks: 12441,
    tags: ["audio", "music", "brainrot"],
  },
  {
    id: "lightskin-stare",
    term: "Lightskin Stare",
    meaning: "An intense sideways gaze meme associated with a smug half-lidded expression.",
    image: "/memes/kym-lightskin-stare.jpg",
    creator: "knowyourmeme",
    bookmarks: 19481,
    tags: ["reaction", "slang", "brainrot"],
  },
  {
    id: "biggest-bird",
    term: "Biggest Bird",
    meaning: "An audio meme from a rant clip, repurposed for hype edits.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 12623,
    tags: ["audio", "brainrot", "viral"],
  },
  {
    id: "omar-the-referee",
    term: "Omar the Referee",
    meaning: "A soccer-referee character featured in absurd 'nan nan nan' edit audio.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 9966,
    tags: ["sports", "absurd", "brainrot"],
  },
  {
    id: "uncanny",
    term: "Uncanny",
    meaning: "The 'Mr. Incredible Becoming Uncanny' meme charting escalating despair.",
    image: "/memes/kym-uncanny.jpg",
    creator: "knowyourmeme",
    bookmarks: 20234,
    tags: ["edit", "reaction", "viral"],
  },
  {
    id: "wholesome-reddit",
    term: "Wholesome Reddit",
    meaning: "Mocking shorthand for saccharine, award-farming 'wholesome 100' Reddit culture.",
    image: "/memes/kym-wholesome-reddit.jpg",
    creator: "knowyourmeme",
    bookmarks: 22600,
    tags: ["reddit", "ironic", "meme"],
  },
  {
    id: "keanu-reeves",
    term: "Keanu Reeves",
    meaning: "Beloved actor widely memed as the internet's 'breathtaking' wholesome icon.",
    image: "/memes/kym-keanu-reeves.jpg",
    creator: "knowyourmeme",
    bookmarks: 24417,
    tags: ["people", "wholesome", "viral"],
  },
  {
    id: "zesty",
    term: "Zesty",
    meaning: "Slang describing overly flamboyant or extra behavior.",
    image: "/memes/kym-zesty.jpg",
    creator: "knowyourmeme",
    bookmarks: 20085,
    tags: ["slang", "genz", "brainrot"],
  },
  {
    id: "poggers",
    term: "Poggers",
    meaning: "Twitch emote and exclamation expressing excitement or hype ('PogChamp').",
    image: "/memes/kym-poggers.jpg",
    creator: "knowyourmeme",
    bookmarks: 25879,
    tags: ["twitch", "slang", "gaming"],
  },
  {
    id: "kumalala-savesta",
    term: "Kumalala Savesta",
    meaning: "A hypnotic looped chant audio used in surreal edits.",
    image: "/memes/kym-kumalala-savesta.jpg",
    creator: "knowyourmeme",
    bookmarks: 12774,
    tags: ["audio", "surreal", "brainrot"],
  },
  {
    id: "glizzy",
    term: "Glizzy",
    meaning: "Slang for a hot dog, spawning 'glizzy' hype and glizzy-gobbler jokes.",
    image: "/memes/kym-glizzy.jpg",
    creator: "knowyourmeme",
    bookmarks: 22021,
    tags: ["food", "slang", "genz"],
  },
  {
    id: "rose-toy",
    nsfw: true,
    term: "Rose Toy",
    meaning: "A rose-shaped gadget that became a coy viral shopping-trend reference.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 15064,
    tags: ["product", "trend", "genz"],
  },
  {
    id: "ankha-zone",
    nsfw: true,
    term: "Ankha Zone",
    meaning: "A viral dance-audio meme referencing an Animal Crossing cat character.",
    image: "/memes/kym-ankha-zone.jpg",
    creator: "knowyourmeme",
    bookmarks: 14674,
    tags: ["audio", "gaming", "brainrot"],
  },
  {
    id: "thug-shaker",
    nsfw: true,
    term: "Thug Shaker",
    meaning: "A dance-clip audio that later became infamous through a document-leak scandal.",
    image: "/memes/kym-thug-shaker.jpg",
    creator: "knowyourmeme",
    bookmarks: 12323,
    tags: ["audio", "dance", "brainrot"],
  },
  {
    id: "dj-khaled",
    term: "DJ Khaled",
    meaning: "Producer famous for shouting his name and motivational 'another one' catchphrases.",
    image: "/memes/kym-dj-khaled.png",
    creator: "knowyourmeme",
    bookmarks: 25598,
    tags: ["people", "music", "viral"],
  },
  {
    id: "sisyphus",
    term: "Sisyphus",
    meaning: "The boulder-rolling Greek figure used as a metaphor for endless futile effort.",
    image: "/memes/kym-sisyphus.jpg",
    creator: "knowyourmeme",
    bookmarks: 20754,
    tags: ["classic", "philosophy", "meme"],
  },
  {
    id: "oceangate",
    term: "OceanGate",
    meaning: "The Titan submersible whose 2023 implosion spawned a wave of dark-humor memes.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 20465,
    tags: ["news", "dark", "viral"],
  },
  {
    id: "shadow-wizard-money-gang",
    term: "Shadow Wizard Money Gang",
    meaning: "The chant 'we love casting spells' turned absurd wizard-crew meme.",
    image: "/memes/kym-shadow-wizard-money-gang.jpg",
    creator: "knowyourmeme",
    bookmarks: 14253,
    tags: ["audio", "absurd", "brainrot"],
  },
  {
    id: "ayo-the-pizza-here",
    term: "Ayo the Pizza Here",
    meaning: "A looping audio gag from a comedy sketch about a pizza delivery.",
    image: "/memes/kym-ayo-the-pizza-here.jpg",
    creator: "knowyourmeme",
    bookmarks: 12983,
    tags: ["audio", "funny", "brainrot"],
  },
  {
    id: "pluh",
    term: "PLUH",
    meaning: "A nonsense exclamation catchphrase from creator YourRAGE.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 11711,
    tags: ["slang", "streamer", "brainrot"],
  },
  {
    id: "t-pose",
    term: "T-Pose",
    meaning: "The default arms-out 3D model stance adopted as a gesture of dominance.",
    image: "/memes/kym-t-pose.jpg",
    creator: "knowyourmeme",
    bookmarks: 22290,
    tags: ["gaming", "reaction", "classic"],
  },
  {
    id: "family-guy-subway-surfers",
    term: "Family Guy + Subway Surfers",
    meaning: "Split-screen 'sludge content' pairing clips with gameplay to hold attention.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 18813,
    tags: ["brainrot", "edit", "viral"],
  },
  {
    id: "nickeh30",
    term: "Nickeh30",
    meaning: "Famously wholesome Fortnite streamer known for saying 'ratio' innocently.",
    image: "/memes/kym-nickeh30.jpg",
    creator: "knowyourmeme",
    bookmarks: 18075,
    tags: ["people", "streamer", "gaming"],
  },
  {
    id: "ratio",
    term: "Ratio",
    meaning: "A reply that outperforms the original post, signalling the take was unpopular.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 23963,
    tags: ["slang", "social", "viral"],
  },
  {
    id: "uwu",
    term: "UwU",
    meaning: "A cutesy emoticon and tone conveying adorable or bashful affection.",
    image: "/memes/kym-uwu.jpg",
    creator: "knowyourmeme",
    bookmarks: 22243,
    tags: ["emoticon", "slang", "classic"],
  },
  {
    id: "opium-bird",
    term: "Opium Bird",
    meaning: "A creepy CGI bird mascot tied to the Opium music label aesthetic.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 11766,
    tags: ["surreal", "music", "brainrot"],
  },
  {
    id: "cg5",
    term: "CG5",
    meaning: "Musician known for catchy meme and video-game inspired original songs.",
    image: "/memes/kym-cg5.jpg",
    creator: "knowyourmeme",
    bookmarks: 16585,
    tags: ["people", "music", "gaming"],
  },
  {
    id: "fortnite-battle-pass",
    term: "Fortnite Battle Pass",
    meaning: "The 'wanna see me buy the Fortnite Battle Pass' bit turned ironic flex.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 20720,
    tags: ["gaming", "ironic", "brainrot"],
  },
  {
    id: "all-my-fellas",
    term: "All My Fellas",
    meaning: "A goofy sing-along audio celebrating 'all my fellas' used in group edits.",
    image: "/memes/kym-all-my-fellas.jpg",
    creator: "knowyourmeme",
    bookmarks: 12374,
    tags: ["audio", "funny", "brainrot"],
  },
  {
    id: "gta-6",
    term: "GTA 6",
    meaning: "Rockstar's hugely anticipated Grand Theft Auto VI, a hype and impatience meme.",
    image: "/memes/kym-gta-6.png",
    creator: "knowyourmeme",
    bookmarks: 23085,
    tags: ["gaming", "hype", "viral"],
  },
  {
    id: "based",
    term: "Based",
    meaning: "Praise for being authentically yourself and unbothered by others' opinions.",
    image: "/memes/kym-based.jpg",
    creator: "knowyourmeme",
    bookmarks: 22531,
    tags: ["slang", "reaction", "viral"],
  },
  {
    id: "cringe",
    term: "Cringe",
    meaning: "Secondhand embarrassment; something awkward or try-hard.",
    image: "/memes/kym-cringe.jpg",
    creator: "knowyourmeme",
    bookmarks: 25002,
    tags: ["slang", "reaction", "classic"],
  },
  {
    id: "kino",
    term: "Kino",
    meaning: "Slang for genuinely great, cinematic-quality film or moments.",
    image: "/memes/kym-kino.jpg",
    creator: "knowyourmeme",
    bookmarks: 16863,
    tags: ["slang", "film", "meme"],
  },
  {
    id: "redpilled",
    term: "Redpilled",
    meaning: "Matrix-derived slang for being 'awakened' to a hidden truth.",
    image: "/memes/kym-redpilled.jpg",
    creator: "knowyourmeme",
    bookmarks: 20049,
    tags: ["slang", "film", "meme"],
  },
  {
    id: "no-nut-november",
    nsfw: true,
    term: "No Nut November",
    meaning: "A tongue-in-cheek month-long abstinence challenge and meme calendar event.",
    image: "/memes/kym-no-nut-november.jpg",
    creator: "knowyourmeme",
    bookmarks: 24846,
    tags: ["challenge", "ironic", "viral"],
  },
  {
    id: "pokenut-november",
    nsfw: true,
    term: "Pokénut November",
    meaning: "A Pokémon-themed parody spin on the No Nut November challenge.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 16131,
    tags: ["challenge", "gaming", "ironic"],
  },
  {
    id: "foot-fetish",
    nsfw: true,
    term: "Foot Fetish",
    meaning: "An ironic Gen Alpha punchline term used absurdly rather than literally.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 14208,
    tags: ["slang", "ironic", "brainrot"],
  },
  {
    id: "f-in-the-chat",
    term: "F in the Chat",
    meaning: "Typing 'F' to pay respects, from a Call of Duty prompt turned universal.",
    image: "/memes/kym-f-in-the-chat.jpg",
    creator: "knowyourmeme",
    bookmarks: 24549,
    tags: ["gaming", "slang", "classic"],
  },
  {
    id: "i-love-lean",
    term: "I Love Lean",
    meaning: "An ironic audio-meme reference tied to trap-music culture.",
    image: "/memes/kym-i-love-lean.jpg",
    creator: "knowyourmeme",
    bookmarks: 14509,
    tags: ["audio", "music", "brainrot"],
  },
  {
    id: "looksmaxxing",
    term: "Looksmaxxing",
    meaning: "Optimizing your appearance through grooming, fitness, and 'maxxing' routines.",
    image: "/memes/kym-looksmaxxing.jpg",
    creator: "knowyourmeme",
    bookmarks: 20226,
    tags: ["looksmax", "trend", "genz"],
  },
  {
    id: "gassy",
    term: "Gassy",
    meaning: "A viral overly-enthusiastic hype reaction sound and expression.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 11591,
    tags: ["reaction", "audio", "brainrot"],
  },
  {
    id: "social-credit",
    term: "Social Credit",
    meaning: "Ironic '+/- social credit' jokes riffing on China's scoring system.",
    image: "/memes/kym-social-credit.jpg",
    creator: "knowyourmeme",
    bookmarks: 21025,
    tags: ["ironic", "political", "meme"],
  },
  {
    id: "bing-chilling",
    term: "Bing Chilling",
    meaning: "John Cena's Mandarin ice-cream ('冰淇淋') clip turned deadpan meme.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 20083,
    tags: ["audio", "funny", "viral"],
  },
  {
    id: "xbox-live",
    term: "Xbox Live",
    meaning: "The '$20 Xbox Live' Vine catchphrase and nostalgic party-chat memories.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 22446,
    tags: ["gaming", "nostalgia", "meme"],
  },
  {
    id: "mrbeast",
    term: "MrBeast",
    meaning: "The world's biggest YouTuber, known for giant giveaways and thumbnail face.",
    image: "/memes/kym-mrbeast.jpg",
    creator: "knowyourmeme",
    bookmarks: 27890,
    tags: ["people", "youtube", "viral"],
  },
  {
    id: "kid-named-finger",
    term: "Kid Named Finger",
    meaning: "The 'you have to hate a kid named Finger?' reaction-panel joke format.",
    image: "/memes/kym-kid-named-finger.jpg",
    creator: "knowyourmeme",
    bookmarks: 20484,
    tags: ["reaction", "funny", "brainrot"],
  },
  {
    id: "better-caul-saul",
    term: "Better Caul Saul",
    meaning: "A pun-based edit of Better Call Saul playing on the word 'call/caul.'",
    image: "/memes/kym-better-caul-saul.jpg",
    creator: "knowyourmeme",
    bookmarks: 15864,
    tags: ["tv", "edit", "meme"],
  },
  {
    id: "i-am-a-surgeon",
    term: "I Am a Surgeon",
    meaning: "A dramatic 'I am a surgeon' line from The Good Doctor turned remix audio.",
    image: "/memes/kym-i-am-a-surgeon.jpg",
    creator: "knowyourmeme",
    bookmarks: 14844,
    tags: ["tv", "audio", "brainrot"],
  },
  {
    id: "hit-or-miss",
    term: "Hit or Miss",
    meaning: "The 'hit or miss, I guess they never miss huh?' TikTok rap that went mega-viral.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 21364,
    tags: ["music", "tiktok", "viral"],
  },
  {
    id: "i-like-ya-cut-g",
    term: "I Like Ya Cut G",
    meaning: "A prank phrase yelled before slapping someone's fresh haircut.",
    image: "/memes/kym-i-like-ya-cut-g.jpg",
    creator: "knowyourmeme",
    bookmarks: 20849,
    tags: ["prank", "slang", "viral"],
  },
  {
    id: "ice-spice",
    term: "Ice Spice",
    meaning: "Rapper known for her signature red curls and viral songs like 'Munch.'",
    image: "/memes/kym-ice-spice.jpg",
    creator: "knowyourmeme",
    bookmarks: 23452,
    tags: ["people", "music", "viral"],
  },
  {
    id: "gooning",
    nsfw: true,
    term: "Gooning",
    meaning: "Ironic Gen Alpha slang for excessive obsessive scrolling or fixation.",
    image: "/memes/kym-gooning.jpg",
    creator: "knowyourmeme",
    bookmarks: 17363,
    tags: ["slang", "ironic", "brainrot"],
  },
  {
    id: "fr",
    term: "Fr",
    meaning: "Short for 'for real,' used to affirm agreement, often doubled as 'fr fr.'",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 27876,
    tags: ["slang", "genz", "classic"],
  },
  {
    id: "we-go-gym",
    term: "We Go Gym",
    meaning: "A gym-motivation catchphrase and audio hyping up workout culture.",
    image: "/memes/kym-we-go-gym.jpg",
    creator: "knowyourmeme",
    bookmarks: 17357,
    tags: ["gym", "motivation", "brainrot"],
  },
  {
    id: "kevin-james",
    term: "Kevin James",
    meaning: "The smirking Kevin James 'Mall Cop' still turned reaction-image staple.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 17624,
    tags: ["people", "reaction", "meme"],
  },
  {
    id: "josh-hutcherson",
    term: "Josh Hutcherson",
    meaning: "The 'Whistle' edit trend built around a spinning Josh Hutcherson face.",
    image: "/placeholder.svg",
    creator: "knowyourmeme",
    bookmarks: 20652,
    tags: ["people", "edit", "brainrot"],
  },
  {
    id: "andy-and-leyley",
    term: "Coffin of Andy and Leyley",
    meaning: "A dark indie horror game about two estranged siblings that drew a cult following.",
    image: "/memes/kym-andy-and-leyley.jpg",
    creator: "knowyourmeme",
    bookmarks: 12465,
    tags: ["gaming", "horror", "brainrot"],
  },
  {
    id: "metal-pipe-falling",
    term: "Metal Pipe Falling",
    meaning: "The ubiquitous clanging metal-pipe sound effect dropped into edits for comedic shock.",
    image: "/memes/kym-metal-pipe-falling.jpg",
    creator: "knowyourmeme",
    bookmarks: 14694,
    tags: ["audio", "edit", "brainrot"],
  },
  {
    id: "tung-tung-tung-sahur",
    term: "Tung Tung Tung Sahur",
    meaning:
      "An AI-generated bat-wielding wooden creature from the 2025 Italian brainrot wave, based on an Indonesian chant for waking people up for Sahur, the pre-dawn Ramadan meal.",
    image: "/memes/kym-tung-tung-sahur.jpg",
    creator: "knowyourmeme",
    bookmarks: 39102,
    tags: ["brainrot", "ai", "viral"],
    fit: "contain",
  },
  {
    id: "67",
    term: "67 (Six Seven)",
    meaning:
      "A nonsensical catchphrase from Skrilla's song \"Doot Doot,\" paired with a see-saw hand gesture. It became Dictionary.com's 2025 Word of the Year.",
    image: "/memes/kym-67.jpg",
    creator: "knowyourmeme",
    bookmarks: 97390,
    tags: ["brainrot", "genz", "viral"],
    fit: "contain",
  },
  {
    id: "red-listening-to-music",
    term: "Red Listening to Music",
    meaning:
      "Red from Angry Birds with an exaggerated ear, signifying attentive listening. It became a popular TikTok reaction for vibing to a song.",
    image: "/memes/kym-red-music.png",
    creator: "knowyourmeme",
    bookmarks: 41280,
    tags: ["brainrot", "reaction", "music", "viral"],
    fit: "contain",
  },
  {
    id: "slay",
    term: "Slay",
    meaning: "To do something exceptionally well or look amazing; a high compliment.",
    image: "/memes/kym-slay.png",
    creator: "knowyourmeme",
    bookmarks: 38120,
    tags: ["genz", "praise", "viral"],
  },
  {
    id: "mid",
    term: "Mid",
    meaning: "Dismissive slang for something mediocre or overhyped that doesn't live up to expectations.",
    image: "/memes/kym-mid.png",
    creator: "knowyourmeme",
    bookmarks: 31540,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "no-cap",
    term: "No Cap",
    meaning: "Means 'no lie' or 'for real'; calling 'cap' means someone is lying.",
    image: "/memes/kym-no-cap.png",
    creator: "knowyourmeme",
    bookmarks: 42980,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "bet",
    term: "Bet",
    meaning: "An affirmation meaning 'okay,' 'sure,' or 'it's on.'",
    image: "/memes/kym-bet.png",
    creator: "knowyourmeme",
    bookmarks: 27760,
    tags: ["genz", "slang"],
  },
  {
    id: "simp",
    term: "Simp",
    meaning: "Someone who does way too much for a person they like, often to a fault.",
    image: "/memes/kym-simp.png",
    creator: "knowyourmeme",
    bookmarks: 51230,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "yeet",
    term: "Yeet",
    meaning: "To throw something with force, or an exclamation of excitement and energy.",
    image: "/memes/kym-yeet.png",
    creator: "knowyourmeme",
    bookmarks: 36410,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "drip",
    term: "Drip",
    meaning: "Stylish, fashionable clothing or all-around swagger.",
    image: "/memes/kym-drip.png",
    creator: "knowyourmeme",
    bookmarks: 44870,
    tags: ["genz", "fashion", "viral"],
  },
  {
    id: "the-ick",
    term: "The Ick",
    meaning: "A sudden feeling of disgust or being turned off by someone you were attracted to.",
    image: "/memes/kym-the-ick.png",
    creator: "knowyourmeme",
    bookmarks: 39560,
    tags: ["genz", "dating", "viral"],
  },
  {
    id: "sheesh",
    term: "Sheesh",
    meaning: "A drawn-out exclamation of admiration, excitement, or being impressed.",
    image: "/memes/kym-sheesh.png",
    creator: "knowyourmeme",
    bookmarks: 33280,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "situationship",
    term: "Situationship",
    meaning: "A romantic relationship that is undefined and lacks real commitment.",
    image: "/memes/kym-situationship.png",
    creator: "knowyourmeme",
    bookmarks: 46390,
    tags: ["genz", "dating", "viral"],
  },
  {
    id: "canon-event",
    term: "Canon Event",
    meaning: "A necessary, often cringe experience you have to go through to become who you are; from Spider-Verse.",
    image: "/memes/kym-canon-event.png",
    creator: "knowyourmeme",
    bookmarks: 40120,
    tags: ["genz", "brainrot", "viral"],
  },
  {
    id: "beige-flag",
    term: "Beige Flag",
    meaning: "A quirky or boring trait in a partner that's neither a dealbreaker nor a plus.",
    image: "/memes/kym-beige-flag.png",
    creator: "knowyourmeme",
    bookmarks: 28940,
    tags: ["genz", "dating", "viral"],
  },
  {
    id: "copium",
    term: "Copium",
    meaning: "Coping with false hope after a loss or disappointment; a blend of 'cope' and 'opium.'",
    image: "/memes/kym-copium.png",
    creator: "knowyourmeme",
    bookmarks: 35670,
    tags: ["genz", "gaming", "viral"],
  },
  {
    id: "skill-issue",
    term: "Skill Issue",
    meaning: "A dismissive way to say a problem is caused by your own lack of skill.",
    image: "/memes/kym-skill-issue.png",
    creator: "knowyourmeme",
    bookmarks: 32180,
    tags: ["genz", "gaming", "viral"],
  },
  {
    id: "spill-the-tea",
    term: "Spill the Tea",
    meaning: "To share gossip or juicy insider information.",
    image: "/memes/kym-spill-the-tea.png",
    creator: "knowyourmeme",
    bookmarks: 37410,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "touch-grass",
    term: "Touch Grass",
    meaning: "Telling someone to log off and reconnect with the real world.",
    image: "/memes/kym-touch-grass.png",
    creator: "knowyourmeme",
    bookmarks: 34090,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "rent-free",
    term: "Rent Free",
    meaning: "When something occupies your thoughts constantly and involuntarily.",
    image: "/memes/kym-rent-free.png",
    creator: "knowyourmeme",
    bookmarks: 29870,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "main-character",
    term: "Main Character Energy",
    meaning: "Acting as though you're the protagonist of your own life story.",
    image: "/memes/kym-main-character.png",
    creator: "knowyourmeme",
    bookmarks: 41760,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "menty-b",
    term: "Menty B",
    meaning: "Playful shorthand for a mental breakdown.",
    image: "/memes/kym-menty-b.png",
    creator: "knowyourmeme",
    bookmarks: 26510,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "bffr",
    term: "BFFR",
    meaning: "Short for 'be for real'; used to express disbelief or call out nonsense.",
    image: "/memes/kym-bffr.png",
    creator: "knowyourmeme",
    bookmarks: 30240,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "cap",
    term: "Cap",
    meaning: "A lie or exaggeration; to 'cap' is to lie.",
    image: "/memes/kym-cap.png",
    creator: "knowyourmeme",
    bookmarks: 31980,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "bop",
    term: "Bop",
    meaning: "A really good, catchy song.",
    image: "/memes/kym-bop.png",
    creator: "knowyourmeme",
    bookmarks: 24570,
    tags: ["genz", "music", "slang"],
  },
  {
    id: "vibe-check",
    term: "Vibe Check",
    meaning: "A spontaneous assessment of someone's mood, attitude, or energy.",
    image: "/memes/kym-vibe-check.png",
    creator: "knowyourmeme",
    bookmarks: 28860,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "cheugy",
    term: "Cheugy",
    meaning: "Describes something out of date or trying too hard to be trendy.",
    image: "/memes/kym-cheugy.png",
    creator: "knowyourmeme",
    bookmarks: 21340,
    tags: ["genz", "slang"],
  },
  {
    id: "glow-up",
    term: "Glow Up",
    meaning: "A dramatic positive transformation in appearance or confidence.",
    image: "/memes/kym-glow-up.png",
    creator: "knowyourmeme",
    bookmarks: 37690,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "gaslighting",
    term: "Gaslighting",
    meaning: "Manipulating someone into doubting their own reality; often used loosely online.",
    image: "/memes/kym-gaslighting.png",
    creator: "knowyourmeme",
    bookmarks: 33410,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "girl-dinner",
    term: "Girl Dinner",
    meaning: "A meal made of random low-effort snacks thrown together instead of cooking.",
    image: "/memes/kym-girl-dinner.png",
    creator: "knowyourmeme",
    bookmarks: 35120,
    tags: ["genz", "food", "viral"],
  },
  {
    id: "goated",
    term: "Goated",
    meaning: "Being the Greatest Of All Time (G.O.A.T.) at something.",
    image: "/memes/kym-goated.png",
    creator: "knowyourmeme",
    bookmarks: 39280,
    tags: ["genz", "praise", "viral"],
  },
  {
    id: "its-giving",
    term: "It's Giving",
    meaning: "Used to describe the vibe or energy something puts out, e.g. 'it's giving main character.'",
    image: "/memes/kym-its-giving.png",
    creator: "knowyourmeme",
    bookmarks: 32760,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "lock-in",
    term: "Lock In",
    meaning: "To fully focus and commit to a task with intense concentration.",
    image: "/memes/kym-lock-in.png",
    creator: "knowyourmeme",
    bookmarks: 34980,
    tags: ["genz", "gaming", "viral"],
  },
  {
    id: "pookie",
    term: "Pookie",
    meaning: "An affectionate pet name for a partner or close friend.",
    image: "/memes/kym-pookie.png",
    creator: "knowyourmeme",
    bookmarks: 27430,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "opp",
    term: "Opp",
    meaning: "Short for opposition; an enemy, rival, or hater.",
    image: "/memes/kym-opp.png",
    creator: "knowyourmeme",
    bookmarks: 25890,
    tags: ["genz", "slang"],
  },
  {
    id: "let-him-cook",
    term: "Let Him Cook",
    meaning: "Telling people to step back and let someone do their thing because they're on a roll.",
    image: "/memes/kym-let-him-cook.png",
    creator: "knowyourmeme",
    bookmarks: 38510,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "fire",
    term: "Fire",
    meaning: "Extremely good, impressive, or high quality.",
    image: "/memes/kym-fire.png",
    creator: "knowyourmeme",
    bookmarks: 30170,
    tags: ["genz", "praise", "slang"],
  },
  {
    id: "salty",
    term: "Salty",
    meaning: "Bitter, upset, or resentful, especially over something minor.",
    image: "/memes/kym-salty.png",
    creator: "knowyourmeme",
    bookmarks: 26640,
    tags: ["genz", "slang"],
  },
  {
    id: "flex",
    term: "Flex",
    meaning: "To show off or boast about something you have or did.",
    image: "/memes/kym-flex.png",
    creator: "knowyourmeme",
    bookmarks: 31050,
    tags: ["genz", "slang", "viral"],
  },
  {
    id: "sus",
    term: "Sus",
    meaning: "Short for suspicious; someone or something that seems shady. Popularized by Among Us.",
    image: "/memes/kym-sus.png",
    creator: "knowyourmeme",
    bookmarks: 43120,
    tags: ["genz", "gaming", "viral"],
  },
  {
    id: "snatched",
    term: "Snatched",
    meaning: "Looking really good, flawless, or perfectly put together.",
    image: "/memes/kym-snatched.png",
    creator: "knowyourmeme",
    bookmarks: 24980,
    tags: ["genz", "fashion", "slang"],
  },
  {
    id: "clapback",
    term: "Clapback",
    meaning: "A sharp, witty response to criticism or an insult.",
    image: "/memes/kym-clapback.png",
    creator: "knowyourmeme",
    bookmarks: 27210,
    tags: ["genz", "slang"],
  },
  {
    id: "understood-the-assignment",
    term: "Understood the Assignment",
    meaning: "Praise for someone who did exactly what was needed and nailed it.",
    image: "/memes/kym-understood-the-assignment.png",
    creator: "knowyourmeme",
    bookmarks: 29650,
    tags: ["genz", "slang", "viral"],
  },
]
